import Head from "next/head";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App - About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>About page</main>
    </div>
  );
};

export default Home;
