name: Cypress Tests

on: [push]
env:
  NEXT_PUBLIC_CMS_URL: ${{secrets.NEXT_PUBLIC_CMS_URL}}
  GRAPHCMS_TOKEN: ${{secrets.GRAPHCMS_TOKEN}}
  NEXT_PUBLIC_CLERK_FRONTEND_API: ${{secrets.NEXT_PUBLIC_CLERK_FRONTEND_API}}
  CLERK_API_KEY: ${{secrets.CLERK_API_KEY}}
  CLERK_JWT_KEY: ${{secrets.CLERK_JWT_KEY}}
  # pass the Cypress Cloud record key as an environment variable
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  # pass GitHub token to allow accurately detecting a build vs a re-run build
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          build: npm run build
          start: npm start
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
